name: psi4flask
channels:
  - conda-forge
  - psi4
dependencies:
  - python=3.8
  - psi4
  - psiresp-base
  - qcelemental
  - numpy
  - rdkit
  - openbabel
  - flask
  - werkzeug
  - ambertools
  - parmed
